TPASS-308:
  describe: |
    #### Data Source

    - This data source (TPASS-308) comprises genetic data from 308 individual _Treponema pallidum_ ssp. _pallidum_, _pertenue_, and _endemicum_ samples, each genotyped against the SS14 reference genome [NC_021508.1](https://www.ncbi.nlm.nih.gov/nuccore/NC_021508.1/).
    - Samples exhibiting mean coverage below 3× or more than 20% no-call (ambiguous) positions have been masked to minimize the impact of inaccurate data.
    - The computed phylogeny is rooted on sample CP004011, the representative of the reference genome.
    - Accompanying metadata includes the sampling <code>Date</code>, <code>Country</code>, and <code>Region</code>; <code>Subspecies</code> and <code>Lineage</code> designations (only for ssp. _pallidum_ as Nichols or SS14); and <code>Mean coverage</code> and <code>Ambiguity</code> to support quality control.
  reference_sample: "CP004011"
  meta_identifier: "sra"
  filter:
    query_cl: "--query-columns ambiguity:float coverage:float --query '(coverage >= 3) & (ambiguity <= 20)'"
  refine:
    year_bounds_cl: "--year-bounds 2023 2000"
    root_cl: "--root CP004011"
  traits:
    columns: "subspecies country region date"
TPASS-2930:
  describe: |
    #### Data Source

    - This data source (TPASS-2930) comprises genetic data from 2,930 individual _Treponema pallidum_ ssp. _pallidum_, _pertenue_, and _endemicum_ samples, each genotyped against the SS14 reference genome [NC_021508.1](https://www.ncbi.nlm.nih.gov/nuccore/NC_021508.1/).
    - Samples exhibiting mean coverage below 3× or more than 20% no-call (ambiguous) positions have been masked to minimize the impact of inaccurate data.
    - The computed phylogeny is rooted on sample CP004011, the representative of the reference genome.
    - Accompanying metadata includes the sampling <code>Date</code>, <code>Country</code>, and <code>Region</code>; <code>Subspecies</code> and <code>Lineage</code> designations (only for ssp. _pallidum_ as Nichols or SS14); and <code>Mean coverage</code> and <code>Ambiguity</code> to support quality control.
  reference_sample: "CP004011"
  meta_identifier: "sra"
  filter:
    query_cl: "--query-columns ambiguity:float coverage:float --query '(coverage >= 3) & (ambiguity <= 20)'"
  refine:
    year_bounds_cl: "--year-bounds 2023 2000"
    root_cl: "--root CP004011"
  traits:
    columns: "subspecies country region date"
subsets:
  snv:
    describe: |
      - Variants are restricted to **single nucleotide variants** (SNVs) to reduce the diversifying effect of low-frequency variants.
  snv-indel:
    describe: |
      - Variants include **single nucleotide variants** (SNVs) and **InDels**, providing insight into the full spectrum of sequence changes.
  snv-masked:
    describe: |
      - Variants are restricted to **single nucleotide variants** (SNVs), and highly recombinant regions are masked to focus on clonal sites that determine conservative pathogen evolution.
