genome_default: &genome_default
  tree:
    method_cl: "--method iqtree --substitution-model HKY+F+ASC+R2 --tree-builder-args='-safe -pathogen'"
  refine:
    clock_rate_cl: "--clock-rate 3.02e-7 --clock-std-dev 8.55e-8"
genomes:
  TPASS-308:
    <<: *genome_default
  TPASS-2930:
    <<: *genome_default
describe:
  genome:
    TPASS-308: |
      #### Genome

      This genome dataset is constructed from whole‐genome variants, featuring the complete phylogenetic context of _T. pallidum_.
      Prior to phylogenetic inference, curated recombinant regions were masked to avoid spurious tree building.
      - The <code>Nucleotide diversity of genome</code> panel features all unmasked positions and individual genes that are also available as gene datasets are highlighted.
      - Clades are currently assigned via a hierarchical‐clustering scheme.
      - Known macrolide resistance mutations, mediated by 23S rRNA mutations G2106A and G2107A, are available via the metadata.
    TPASS-2930: |
      #### Genome

      This genome dataset is constructed from whole‐genome variants, featuring the complete phylogenetic context of _T. pallidum_.
      Prior to phylogenetic inference, curated recombinant regions were masked to avoid spurious tree building.
      - The <code>Nucleotide diversity of genome</code> panel features all unmasked positions and individual genes that are also available as gene datasets are highlighted.
      - Clades are currently assigned via a hierarchical‐clustering scheme.
      - Known macrolide resistance mutations, mediated by 23S rRNA mutations G2106A and G2107A, are available via the metadata.