seed: 1
musial: "/mnt/c/Users/siha/Desktop/Tools/MUSIAL-v2.4.1.jar"
refine:
  precision: 3
  iterations: 2
export:
  title: "Global perspective on Treponema pallidum"
  maintainers: "'Simon Hackl <https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/lehrstuehle/integrative-transkriptomik/gruppe/simon-hackl/>'"
  build_url: "https://github.com/Integrative-Transcriptomics/Nextstrain-TrepoGen"
describe:
  resources: |
    ##### Further resources

    We are working diligently to provide resources for extended data/sequence access.
  background: |
    ##### Project Background

    Syphilis is a resurging global health threat caused by _Treponema pallidum_ ssp. _pallidum_, with additional disease burden from the closely related subspecies _pertenue_ and _endemicum_, the causative agents of yaws and bejel, respectively.
    By 2025 whole genome sequencing data for more than 3,000 _T. pallidum_ strains were available in the NCBI Sequence Read Archive.
    However, more than 80% of these lack publicly available genome assemblies and, more critically, systematic annotation.
    This severely limits their utility for molecular epidemiology, resistance surveillance, and vaccine development.
    We aim at democratizing access to _T. pallidum_ genomic diversity data by developing and maintaining unified, community-facing Nextstrain datasets for epidemiological surveillance, comparative evolutionary analysis and facilitated data sharing; with a special emphasis on tracking outer membrane protein (OMP) diversity relevant for vaccine design.
  funding: |
    ##### Funding and Provenance
    
    This project receives funding [To support the development of a broadly effective syphilis vaccine (INV-072205)](https://www.gatesfoundation.org/about/committed-grants/2024/12/inv-072205) by the _Gates Foundation_.
    We gratefully acknowledge the authors, originating and submitting laboratories of the genetic sequences and metadata for sharing their work.
    Data producers should be named where possible and cooperation should be sought in certain circumstances.
    Please avoid scooping the work of others and reach out if uncertain.
